# Generated by Django 5.2.6 on 2025-09-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista'), ('consultor', 'Consultor')], default='analista', help_text='Rol del usuario que determina sus permisos en el sistema', max_length=50),
        ),
    ]
