services:
  - type: web
    name: sigaa-web
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn sigaa.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
