# Generated by Django 5.2.5 on 2025-08-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliados', '0001_initial'),
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('sueldo_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliados.afiliado')),
                ('tabla_salarial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.tablasalarial')),
            ],
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sueldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='liquidacion.sueldo')),
            ],
        ),
    ]
