# Generated by Django 5.2.5 on 2025-08-26 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0004_remove_afiliado_numero_hijos_afiliado_nombre_hijos'),
        ('liquidacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name='aporte',
            old_name='entidad',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='aporte',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterUniqueTogether(
            name='sueldo',
            unique_together={('afiliado', 'anio')},
        ),
        migrations.CreateModel(
            name='BonificacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sueldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonificaciones', to='liquidacion.sueldo')),
            ],
        ),
        migrations.CreateModel(
            name='TablaSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('grado', models.CharField(max_length=10)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'unique_together': {('anio', 'grado')},
            },
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='tabla_salarial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidacion.tablasalarial'),
        ),
    ]
