# Generated by Django 5.2.5 on 2025-08-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0002_bonificacion_rename_entidad_aporte_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablasalarial',
            name='sueldo_con_bonificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
