# Generated by Django 5.2.6 on 2025-09-14 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0005_alter_afiliado_options_and_more'),
        ('liquidacion', '0003_tablasalarial_sueldo_con_bonificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aporte',
            options={'ordering': ['sueldo', 'nombre'], 'verbose_name': 'Aporte', 'verbose_name_plural': 'Aportes'},
        ),
        migrations.AlterModelOptions(
            name='bonificacion',
            options={'ordering': ['anio', 'descripcion'], 'verbose_name': 'Bonificación', 'verbose_name_plural': 'Bonificaciones'},
        ),
        migrations.AlterModelOptions(
            name='bonificacionpago',
            options={'ordering': ['sueldo', 'descripcion'], 'verbose_name': 'Bonificación de Pago', 'verbose_name_plural': 'Bonificaciones de Pago'},
        ),
        migrations.AlterModelOptions(
            name='sueldo',
            options={'ordering': ['-anio', 'afiliado__nombre_completo'], 'verbose_name': 'Sueldo', 'verbose_name_plural': 'Sueldos'},
        ),
        migrations.AlterModelOptions(
            name='tablasalarial',
            options={'ordering': ['anio', 'grado'], 'verbose_name': 'Tabla Salarial', 'verbose_name_plural': 'Tablas Salariales'},
        ),
        migrations.AlterField(
            model_name='aporte',
            name='nombre',
            field=models.CharField(help_text='Nombre del aporte (ADEMACOR o FAMICOR)', max_length=50),
        ),
        migrations.AlterField(
            model_name='aporte',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje del aporte sobre el sueldo neto', max_digits=6),
        ),
        migrations.AlterField(
            model_name='aporte',
            name='sueldo',
            field=models.ForeignKey(help_text='Sueldo sobre el cual se calcula el aporte', on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='liquidacion.sueldo'),
        ),
        migrations.AlterField(
            model_name='aporte',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor calculado del aporte en pesos', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bonificacion',
            name='anio',
            field=models.IntegerField(help_text='Año de vigencia de la bonificación'),
        ),
        migrations.AlterField(
            model_name='bonificacion',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la bonificación (ej: Bonificación especial COVID)', max_length=100),
        ),
        migrations.AlterField(
            model_name='bonificacion',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de bonificación a aplicar', max_digits=5),
        ),
        migrations.AlterField(
            model_name='bonificacionpago',
            name='anio',
            field=models.IntegerField(help_text='Año en que se aplicó la bonificación'),
        ),
        migrations.AlterField(
            model_name='bonificacionpago',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción del tipo de bonificación (cargo, antigüedad, educación, etc.)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bonificacionpago',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto calculado de la bonificación en pesos', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bonificacionpago',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de bonificación aplicado sobre el salario base', max_digits=6),
        ),
        migrations.AlterField(
            model_name='bonificacionpago',
            name='sueldo',
            field=models.ForeignKey(help_text='Sueldo al que se aplica esta bonificación', on_delete=django.db.models.deletion.CASCADE, related_name='bonificaciones', to='liquidacion.sueldo'),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='afiliado',
            field=models.ForeignKey(help_text='Afiliado al que pertenece este sueldo', on_delete=django.db.models.deletion.CASCADE, to='afiliados.afiliado'),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='anio',
            field=models.IntegerField(help_text='Año del sueldo calculado'),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='sueldo_neto',
            field=models.DecimalField(decimal_places=2, help_text='Sueldo neto final calculado con todas las bonificaciones', max_digits=12),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='tabla_salarial',
            field=models.ForeignKey(blank=True, help_text='Tabla salarial usada como base para el cálculo', null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidacion.tablasalarial'),
        ),
        migrations.AlterField(
            model_name='tablasalarial',
            name='anio',
            field=models.IntegerField(help_text='Año de vigencia de la tabla salarial'),
        ),
        migrations.AlterField(
            model_name='tablasalarial',
            name='grado',
            field=models.CharField(help_text='Grado del escalafón docente (A, B, 1-14)', max_length=10),
        ),
        migrations.AlterField(
            model_name='tablasalarial',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, help_text='Salario base oficial para el grado y año', max_digits=12),
        ),
        migrations.AlterField(
            model_name='tablasalarial',
            name='sueldo_con_bonificacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salario base + aumento por grado (calculado automáticamente)', max_digits=12, null=True),
        ),
    ]
