# Generated by Django 3.2.20 on 2025-11-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0004_alter_aporte_options_alter_bonificacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del parámetro (ej: APORTE_ADEMACOR, BONIF_ANTIGUEDAD)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del parámetro', max_length=100)),
                ('tipo', models.CharField(choices=[('APORTE', 'Aporte'), ('BONIF', 'Bonificación'), ('OTRO', 'Otro')], default='OTRO', help_text='Tipo de parámetro', max_length=10)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=4, help_text='Valor numérico del parámetro (para porcentajes o valores fijos)', max_digits=10, null=True)),
                ('valor_texto', models.TextField(blank=True, help_text='Valor de texto del parámetro (para descripciones o valores no numéricos)', null=True)),
                ('anio_vigencia', models.IntegerField(default=0, help_text='Año de vigencia del parámetro (0 para parámetros permanentes)')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el parámetro está activo y debe ser considerado en los cálculos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetro de Liquidación',
                'verbose_name_plural': 'Parámetros de Liquidación',
                'ordering': ['tipo', 'codigo'],
            },
        ),
        migrations.AlterModelOptions(
            name='bonificacionpago',
            options={'ordering': ['anio', 'sueldo__afiliado__nombre_completo'], 'verbose_name': 'Bonificación de Pago', 'verbose_name_plural': 'Bonificaciones de pago'},
        ),
        migrations.AlterUniqueTogether(
            name='bonificacionpago',
            unique_together={('sueldo', 'descripcion')},
        ),
    ]
