# Generated by Django 3.2.20 on 2025-11-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0009_auto_20251120_1046'),
        ('liquidacion', '0005_auto_20251103_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporte',
            name='nombre',
            field=models.CharField(help_text='Nombre del aporte (ADEMACOR o FAMECOR)', max_length=50),
        ),
        migrations.CreateModel(
            name='SueldoAdemacor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(help_text='Año del sueldo calculado')),
                ('sueldo_neto', models.DecimalField(decimal_places=2, help_text='Sueldo neto final calculado con todas las bonificaciones', max_digits=12)),
                ('afiliado_ademacor', models.ForeignKey(help_text='Afiliado ADEMACOR al que pertenece este sueldo', on_delete=django.db.models.deletion.CASCADE, related_name='sueldos_ademacor', to='afiliados.datosademacor')),
                ('tabla_salarial', models.ForeignKey(blank=True, help_text='Tabla salarial usada como base para el cálculo', null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidacion.tablasalarial')),
            ],
            options={
                'verbose_name': 'Sueldo ADEMACOR',
                'verbose_name_plural': 'Sueldos ADEMACOR',
                'ordering': ['-anio', 'afiliado_ademacor__nombre_completo'],
                'unique_together': {('afiliado_ademacor', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='AporteAdemacor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del aporte (ADEMACOR o FAMECOR)', max_length=50)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje del aporte sobre el sueldo neto', max_digits=6)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor calculado del aporte en pesos', max_digits=12)),
                ('sueldo_ademacor', models.ForeignKey(help_text='Sueldo ADEMACOR sobre el cual se calcula el aporte', on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='liquidacion.sueldoademacor')),
            ],
            options={
                'verbose_name': 'Aporte ADEMACOR',
                'verbose_name_plural': 'Aportes ADEMACOR',
                'ordering': ['sueldo_ademacor', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='BonificacionPagoAdemacor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(help_text='Año en que se aplicó la bonificación')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción del tipo de bonificación (cargo, antigüedad, educación, etc.)', max_length=150, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de bonificación aplicado sobre el salario base', max_digits=6)),
                ('monto', models.DecimalField(decimal_places=2, default=0, help_text='Monto calculado de la bonificación en pesos', max_digits=12)),
                ('sueldo_ademacor', models.ForeignKey(help_text='Sueldo ADEMACOR al que se aplica esta bonificación', on_delete=django.db.models.deletion.CASCADE, related_name='bonificaciones', to='liquidacion.sueldoademacor')),
            ],
            options={
                'verbose_name': 'Bonificación de Pago ADEMACOR',
                'verbose_name_plural': 'Bonificaciones de Pago ADEMACOR',
                'ordering': ['anio', 'sueldo_ademacor__afiliado_ademacor__nombre_completo'],
                'unique_together': {('sueldo_ademacor', 'descripcion')},
            },
        ),
    ]
