# Generated by Django 6.0.3 on 2026-03-05 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0011_alter_datosorganizacion_options_and_more'),
        ('liquidacion', '0007_rename_enterprise_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aporteorganizacion',
            options={'ordering': ['sueldo_organizacion', 'nombre'], 'verbose_name': 'Aporte Organización', 'verbose_name_plural': 'Aportes Organización'},
        ),
        migrations.AlterModelOptions(
            name='bonificacionpagoorganizacion',
            options={'ordering': ['anio', 'sueldo_organizacion__afiliado_organizacion__nombre_completo'], 'verbose_name': 'Bonificación de Pago Organización', 'verbose_name_plural': 'Bonificaciones de Pago Organización'},
        ),
        migrations.AlterModelOptions(
            name='sueldoorganizacion',
            options={'ordering': ['-anio', 'afiliado_organizacion__nombre_completo'], 'verbose_name': 'Sueldo Organización', 'verbose_name_plural': 'Sueldos Organización'},
        ),
        migrations.AlterField(
            model_name='aporte',
            name='nombre',
            field=models.CharField(help_text='Nombre del aporte (aporte_institucional o aporte_fondo)', max_length=50),
        ),
        migrations.AlterField(
            model_name='aporteorganizacion',
            name='nombre',
            field=models.CharField(help_text='Nombre del aporte (aporte_institucional o aporte_fondo)', max_length=50),
        ),
        migrations.AlterField(
            model_name='aporteorganizacion',
            name='sueldo_organizacion',
            field=models.ForeignKey(help_text='Sueldo de organización externa sobre el cual se calcula el aporte', on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='liquidacion.sueldoorganizacion'),
        ),
        migrations.AlterField(
            model_name='bonificacionpagoorganizacion',
            name='sueldo_organizacion',
            field=models.ForeignKey(help_text='Sueldo de organización externa al que se aplica esta bonificación', on_delete=django.db.models.deletion.CASCADE, related_name='bonificaciones', to='liquidacion.sueldoorganizacion'),
        ),
        migrations.AlterField(
            model_name='sueldoorganizacion',
            name='afiliado_organizacion',
            field=models.ForeignKey(help_text='Afiliado de organización externa al que pertenece este sueldo', on_delete=django.db.models.deletion.CASCADE, related_name='sueldos_organizacion', to='afiliados.datosorganizacion'),
        ),
    ]
