# Generated by Django 5.2.6 on 2025-09-14 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_generado'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AddField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción adicional del contenido del reporte', null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo del reporte generado', null=True, upload_to='reportes/'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_generado',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de generación del reporte'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='generado_por',
            field=models.ForeignKey(help_text='Usuario que generó el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV'), ('sueldos', 'Reporte de Sueldos'), ('aportes', 'Reporte de Aportes'), ('afiliados', 'Reporte de Afiliados')], help_text='Tipo de reporte generado (Excel, PDF, CSV, etc.)', max_length=50),
        ),
    ]
