# Generated by Django 3.2.20 on 2025-10-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reporte_options_reporte_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='archivo_excel',
            field=models.FileField(blank=True, help_text='Archivo Excel del reporte (si aplica)', null=True, upload_to='reportes/'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Archivo PDF del reporte (si aplica)', null=True, upload_to='reportes/'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV'), ('sueldos', 'Reporte de Sueldos'), ('aportes', 'Reporte de Aportes'), ('afiliados', 'Reporte de Afiliados'), ('diferencias_secretaria_ademacor', 'Diferencias Secretaría vs ADEMACOR')], help_text='Tipo de reporte generado (Excel, PDF, CSV, etc.)', max_length=50),
        ),
    ]
