# Generated by Django 3.2.20 on 2025-10-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_auto_20251006_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el reporte está activo (visible)'),
        ),
    ]
