# Generated by Django 3.2.20 on 2025-11-19 14:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0005_reporte_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAportesTotales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(help_text='Año del reporte')),
                ('mes', models.IntegerField(help_text='Mes del reporte (1-12)')),
                ('total_ademacor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de aportes ADEMACOR del período', max_digits=15)),
                ('total_famecor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de aportes FAMECOR del período', max_digits=15)),
                ('total_general', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total general de todos los aportes', max_digits=15)),
                ('cantidad_afiliados', models.IntegerField(default=0, help_text='Cantidad de afiliados con aportes en el período')),
                ('cantidad_aportes_ademacor', models.IntegerField(default=0, help_text='Cantidad de aportes ADEMACOR procesados')),
                ('cantidad_aportes_famecor', models.IntegerField(default=0, help_text='Cantidad de aportes FAMECOR procesados')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora cuando se calcularon los totales')),
                ('archivo_excel', models.FileField(blank=True, help_text='Archivo Excel con el reporte detallado', null=True, upload_to='reportes/aportes_totales/')),
                ('archivo_pdf', models.FileField(blank=True, help_text='Archivo PDF con el reporte detallado', null=True, upload_to='reportes/aportes_totales/')),
                ('calculado_por', models.ForeignKey(help_text='Usuario que generó el cálculo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Totales de Aportes',
                'verbose_name_plural': 'Reportes de Totales de Aportes',
                'ordering': ['-anio', '-mes', '-fecha_calculo'],
                'unique_together': {('anio', 'mes')},
            },
        ),
    ]
