# Generated by Django 6.0.3 on 2026-03-06 21:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_reporteaportestotales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteaportestotales',
            name='cantidad_aportes_ademacor',
        ),
        migrations.RemoveField(
            model_name='reporteaportestotales',
            name='total_ademacor',
        ),
        migrations.AddField(
            model_name='reporteaportestotales',
            name='cantidad_aportes_organizacion',
            field=models.IntegerField(default=0, help_text='Cantidad de aportes de Organización procesados'),
        ),
        migrations.AddField(
            model_name='reporteaportestotales',
            name='total_organizacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de aportes de Organización del período', max_digits=15),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV'), ('sueldos', 'Reporte de Sueldos'), ('aportes', 'Reporte de Aportes'), ('afiliados', 'Reporte de Afiliados'), ('diferencias_secretaria_organizacion', 'Diferencias Secretaría vs Organización')], help_text='Tipo de reporte generado (Excel, PDF, CSV, etc.)', max_length=50),
        ),
    ]
