# Generated by Django 5.2.6 on 2025-09-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonificacion',
            options={'ordering': ['anio', 'descripcion'], 'verbose_name': 'Bonificación (Tablas)', 'verbose_name_plural': 'Bonificaciones (Tablas)'},
        ),
        migrations.AlterModelOptions(
            name='tablasalarial',
            options={'ordering': ['anio', 'grado'], 'verbose_name': 'Tabla Salarial (Tablas)', 'verbose_name_plural': 'Tablas Salariales (Tablas)'},
        ),
        migrations.AlterField(
            model_name='bonificacion',
            name='anio',
            field=models.IntegerField(help_text='Año de vigencia de la bonificación'),
        ),
        migrations.AlterField(
            model_name='bonificacion',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la bonificación', max_length=100),
        ),
        migrations.AlterField(
            model_name='bonificacion',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de bonificación a aplicar', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tablasalarial',
            name='anio',
            field=models.IntegerField(help_text='Año de vigencia de la tabla salarial'),
        ),
        migrations.AlterField(
            model_name='tablasalarial',
            name='grado',
            field=models.CharField(help_text='Grado del escalafón docente', max_length=10),
        ),
        migrations.AlterField(
            model_name='tablasalarial',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, help_text='Salario base para el grado y año especificado', max_digits=12),
        ),
    ]
