# Generated by Django 5.2.5 on 2025-08-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afiliado',
            old_name='identificacion',
            new_name='cedula',
        ),
    ]
