# Generated by Django 5.2.5 on 2025-08-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0002_rename_identificacion_afiliado_cedula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afiliado',
            old_name='apellidos',
            new_name='ciudad_de_nacimiento',
        ),
        migrations.RenameField(
            model_name='afiliado',
            old_name='nombres',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='afiliado',
            old_name='escalafon',
            new_name='grado_escalafon',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='regimen',
        ),
        migrations.AddField(
            model_name='afiliado',
            name='años_de_servicio_docente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='cargos_desempenñados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='estudios_posgrado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='experiencia_docente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='institucion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='nombre_completo',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afiliado',
            name='nombre_conyuge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='numero_hijos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='otros_titulos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='titulo_posgrado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='ultimo_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
