# Generated by Django 5.2.5 on 2025-08-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0003_rename_apellidos_afiliado_ciudad_de_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliado',
            name='numero_hijos',
        ),
        migrations.AddField(
            model_name='afiliado',
            name='nombre_hijos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
