# Generated by Django 5.2.6 on 2025-09-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0004_remove_afiliado_numero_hijos_afiliado_nombre_hijos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afiliado',
            options={'ordering': ['nombre_completo'], 'verbose_name': 'Afiliado', 'verbose_name_plural': 'Afiliados'},
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='años_de_servicio_docente',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='cargos_desempenñados',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='experiencia_docente',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='ultimo_cargo',
        ),
        migrations.AddField(
            model_name='afiliado',
            name='anos_servicio',
            field=models.IntegerField(blank=True, help_text='Años de servicio en la institución. Determina bonificación por antigüedad', null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='cargo_desempenado',
            field=models.CharField(blank=True, help_text='Cargo actual: rector, decano, director, coordinador, docente, etc. Afecta bonificaciones', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro'),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='titulo_pregrado',
            field=models.CharField(blank=True, help_text='Título de pregrado obtenido', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el afiliado está activo en el sistema'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='cedula',
            field=models.CharField(help_text='Número de cédula de identidad único del afiliado', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='ciudad_de_nacimiento',
            field=models.CharField(help_text='Ciudad donde nació el afiliado', max_length=100),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='departamento',
            field=models.CharField(help_text='Departamento de residencia o trabajo del afiliado', max_length=100),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección de residencia completa', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='edad',
            field=models.IntegerField(blank=True, help_text='Edad actual del afiliado (calculada o importada)', null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico de contacto', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='estado_civil',
            field=models.CharField(blank=True, help_text='Estado civil: soltero, casado, divorciado, viudo, etc.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='estudios_posgrado',
            field=models.CharField(blank=True, help_text='Descripción detallada de estudios de posgrado realizados', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha de ingreso a la institución. Usado para calcular años de servicio', null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del afiliado', null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='grado_escalafon',
            field=models.CharField(blank=True, help_text='Grado en el escalafón docente (1-14). Determina el salario base', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='nombre_completo',
            field=models.CharField(help_text='Nombre completo del afiliado (nombres y apellidos)', max_length=100),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='nombre_conyuge',
            field=models.CharField(blank=True, help_text='Nombre completo del cónyuge si aplica', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='nombre_hijos',
            field=models.CharField(blank=True, help_text='Nombres de los hijos separados por comas', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='otros_titulos',
            field=models.CharField(blank=True, help_text='Otros títulos, certificaciones o estudios adicionales', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='titulo_posgrado',
            field=models.CharField(blank=True, help_text='Título de posgrado principal. Usado para detectar maestría/doctorado', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='afiliado',
            index=models.Index(fields=['cedula'], name='afiliados_a_cedula_fa5997_idx'),
        ),
        migrations.AddIndex(
            model_name='afiliado',
            index=models.Index(fields=['grado_escalafon'], name='afiliados_a_grado_e_a525db_idx'),
        ),
        migrations.AddIndex(
            model_name='afiliado',
            index=models.Index(fields=['activo'], name='afiliados_a_activo_f62399_idx'),
        ),
    ]
