# Generated by Django 3.2.20 on 2025-09-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0005_alter_afiliado_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliado',
            name='departamento',
        ),
        migrations.AddField(
            model_name='afiliado',
            name='municipio',
            field=models.CharField(blank=True, help_text='Municipio de residencia o trabajo del afiliado', max_length=100, null=True),
        ),
    ]
