# Generated by Django 3.2.20 on 2025-10-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0006_auto_20250927_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAdemacor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(help_text='Número de cédula de identidad', max_length=20, unique=True)),
                ('nombre_completo', models.CharField(help_text='Nombre completo (nombres y apellidos)', max_length=100)),
                ('municipio', models.CharField(blank=True, help_text='Municipio de residencia o trabajo', max_length=100, null=True)),
                ('descripcion', models.CharField(default='ademacor', help_text='Tipo de datos - constante: ademacor', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro')),
            ],
            options={
                'verbose_name': 'Dato de ADEMACOR',
                'verbose_name_plural': 'Datos de ADEMACOR',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='DatosSecretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(help_text='Número de cédula de identidad', max_length=20, unique=True)),
                ('nombre_completo', models.CharField(help_text='Nombre completo (nombres y apellidos)', max_length=100)),
                ('municipio', models.CharField(blank=True, help_text='Municipio de residencia o trabajo', max_length=100, null=True)),
                ('descripcion', models.CharField(default='secretaria', help_text='Tipo de datos - constante: secretaria', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro')),
            ],
            options={
                'verbose_name': 'Dato de Secretaría',
                'verbose_name_plural': 'Datos de Secretaría',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
