# Generated by Django 3.2.20 on 2025-10-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0007_datosademacor_datossecretaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(help_text='Número de cédula de identidad único del desafiliado', max_length=20, unique=True)),
                ('nombre_completo', models.CharField(help_text='Nombre completo del desafiliado (nombres y apellidos)', max_length=100)),
                ('municipio', models.CharField(blank=True, help_text='Municipio de residencia o trabajo del desafiliado', max_length=100, null=True)),
                ('ciudad_de_nacimiento', models.CharField(help_text='Ciudad donde nació el desafiliado', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del desafiliado', null=True)),
                ('edad', models.IntegerField(blank=True, help_text='Edad actual del desafiliado (calculada o importada)', null=True)),
                ('estado_civil', models.CharField(blank=True, help_text='Estado civil: soltero, casado, divorciado, viudo, etc.', max_length=20, null=True)),
                ('nombre_conyuge', models.CharField(blank=True, help_text='Nombre completo del cónyuge si aplica', max_length=100, null=True)),
                ('nombre_hijos', models.CharField(blank=True, help_text='Nombres de los hijos separados por comas', max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, help_text='Dirección de residencia completa', max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico de contacto', max_length=254, null=True)),
                ('grado_escalafon', models.CharField(blank=True, help_text='Grado en el escalafón docente (1-14). Determina el salario base', max_length=10, null=True)),
                ('cargo_desempenado', models.CharField(blank=True, help_text='Cargo desempeñado al momento de la desafiliación', max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, help_text='Fecha de ingreso a la institución. Usado para calcular años de servicio', null=True)),
                ('anos_servicio', models.IntegerField(blank=True, help_text='Años de servicio en la institución al momento de la desafiliación', null=True)),
                ('titulo_pregrado', models.CharField(blank=True, help_text='Título de pregrado obtenido', max_length=100, null=True)),
                ('titulo_posgrado', models.CharField(blank=True, help_text='Título de posgrado principal. Usado para detectar maestría/doctorado', max_length=100, null=True)),
                ('estudios_posgrado', models.CharField(blank=True, help_text='Descripción detallada de estudios de posgrado realizados', max_length=200, null=True)),
                ('otros_titulos', models.CharField(blank=True, help_text='Otros títulos, certificaciones o estudios adicionales', max_length=200, null=True)),
                ('motivo_desafiliacion', models.TextField(help_text='Motivo de la desafiliación del sistema')),
                ('activo', models.BooleanField(default=False, help_text='Indica si el desafiliado está activo en el sistema (siempre False)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro')),
                ('fecha_desafiliacion', models.DateField(auto_now_add=True, help_text='Fecha en que se registró la desafiliación')),
            ],
            options={
                'verbose_name': 'Desafiliado',
                'verbose_name_plural': 'Desafiliados',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.AddIndex(
            model_name='desafiliado',
            index=models.Index(fields=['cedula'], name='afiliados_d_cedula_6fe9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='desafiliado',
            index=models.Index(fields=['activo'], name='afiliados_d_activo_7fd282_idx'),
        ),
    ]
