# Generated by Django 3.2.20 on 2025-11-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0008_auto_20251031_0945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosSecretaria',
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el afiliado ADEMACOR está activo en el sistema'),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='anos_servicio',
            field=models.IntegerField(blank=True, help_text='Años de servicio en la institución. Determina bonificación por antigüedad', null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='cargo_desempenado',
            field=models.CharField(blank=True, help_text='Cargo actual: rector, decano, director, coordinador, docente, etc. Afecta bonificaciones', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='ciudad_de_nacimiento',
            field=models.CharField(blank=True, help_text='Ciudad donde nació el afiliado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección de residencia completa', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='edad',
            field=models.IntegerField(blank=True, help_text='Edad actual del afiliado (calculada o importada)', null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico de contacto', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='estado_civil',
            field=models.CharField(blank=True, help_text='Estado civil: soltero, casado, divorciado, viudo, etc.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='estudios_posgrado',
            field=models.CharField(blank=True, help_text='Descripción detallada de estudios de posgrado realizados', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha de ingreso a la institución. Usado para calcular años de servicio', null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del afiliado', null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='grado_escalafon',
            field=models.CharField(blank=True, help_text='Grado en el escalafón docente (1-14). Determina el salario base', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='nombre_conyuge',
            field=models.CharField(blank=True, help_text='Nombre completo del cónyuge si aplica', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='nombre_hijos',
            field=models.CharField(blank=True, help_text='Nombres de los hijos separados por comas', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='otros_titulos',
            field=models.CharField(blank=True, help_text='Otros títulos, certificaciones o estudios adicionales', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='titulo_posgrado',
            field=models.CharField(blank=True, help_text='Título de posgrado principal. Usado para detectar maestría/doctorado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datosademacor',
            name='titulo_pregrado',
            field=models.CharField(blank=True, help_text='Título de pregrado obtenido', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datosademacor',
            name='cedula',
            field=models.CharField(help_text='Número de cédula de identidad único del afiliado', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='datosademacor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', null=True),
        ),
        migrations.AlterField(
            model_name='datosademacor',
            name='municipio',
            field=models.CharField(blank=True, help_text='Municipio de residencia o trabajo del afiliado', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datosademacor',
            name='nombre_completo',
            field=models.CharField(help_text='Nombre completo del afiliado (nombres y apellidos)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='datosademacor',
            index=models.Index(fields=['cedula'], name='afiliados_d_cedula_928077_idx'),
        ),
        migrations.AddIndex(
            model_name='datosademacor',
            index=models.Index(fields=['grado_escalafon'], name='afiliados_d_grado_e_a490b4_idx'),
        ),
        migrations.AddIndex(
            model_name='datosademacor',
            index=models.Index(fields=['activo'], name='afiliados_d_activo_92f42d_idx'),
        ),
    ]
