# Generated by Django 6.0.3 on 2026-03-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0010_rename_enterprise_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosorganizacion',
            options={'ordering': ['nombre_completo'], 'verbose_name': 'Dato de Organización', 'verbose_name_plural': 'Datos de Organización'},
        ),
        migrations.RenameIndex(
            model_name='datosorganizacion',
            new_name='afiliados_d_cedula_fbb60e_idx',
            old_name='afiliados_d_cedula_928077_idx',
        ),
        migrations.RenameIndex(
            model_name='datosorganizacion',
            new_name='afiliados_d_grado_e_650600_idx',
            old_name='afiliados_d_grado_e_a490b4_idx',
        ),
        migrations.RenameIndex(
            model_name='datosorganizacion',
            new_name='afiliados_d_activo_81cb61_idx',
            old_name='afiliados_d_activo_92f42d_idx',
        ),
        migrations.AlterField(
            model_name='datosorganizacion',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el afiliado de organización externa está activo en el sistema'),
        ),
    ]
